/**
 * AWS Lambda – Flood Risk SNS Alert Sender
 * Deploy this on AWS Lambda, triggered by API Gateway POST /alert
 *
 * Environment Variables to set in Lambda console:
 *   SNS_TOPIC_ARN  = arn:aws:sns:us-east-1:ACCOUNT_ID:FloodRiskAlerts
 *   AWS_REGION     = us-east-1  (Lambda sets this automatically)
 *   ALLOWED_ORIGIN = https://your-cloudfront-domain.cloudfront.net
 *
 * IAM Role needs: sns:Publish, logs:CreateLogGroup, logs:PutLogEvents
 */

const { SNSClient, PublishCommand, SubscribeCommand } = require("@aws-sdk/client-sns");

const sns = new SNSClient({ region: process.env.AWS_REGION || "us-east-1" });
const TOPIC_ARN = process.env.SNS_TOPIC_ARN;
const ALLOWED_ORIGIN = process.env.ALLOWED_ORIGIN || "*";

exports.handler = async (event) => {
  const method = event.requestContext?.http?.method || event.httpMethod;

  // CORS pre-flight
  const headers = {
    "Access-Control-Allow-Origin": ALLOWED_ORIGIN,
    "Access-Control-Allow-Methods": "POST, OPTIONS",
    "Access-Control-Allow-Headers": "Content-Type",
    "Content-Type": "application/json"
  };

  if (method === "OPTIONS") {
    return { statusCode: 200, headers, body: "" };
  }

  try {
    const body = JSON.parse(event.body || "{}");
    const { email, location, risk, rainfall, waterLevel, timestamp } = body;

    if (!email || !location || !risk) {
      return {
        statusCode: 400, headers,
        body: JSON.stringify({ error: "Missing required fields: email, location, risk" })
      };
    }

    // ── Step 1: Subscribe the email to SNS topic (idempotent) ──────────────
    // SNS will send a confirmation email on first subscription.
    await sns.send(new SubscribeCommand({
      TopicArn: TOPIC_ARN,
      Protocol: "email",
      Endpoint: email,
      ReturnSubscriptionArn: false
    }));

    // ── Step 2: Build the alert message ────────────────────────────────────
    const isHigh = risk === "HIGH";
    const isMod  = risk === "MODERATE";

    const subject = isHigh
      ? `🚨 FLOOD ALERT: HIGH RISK detected at ${location}`
      : isMod
      ? `⚡ FLOOD WARNING: Moderate risk at ${location}`
      : `✅ Flood Status: LOW RISK at ${location}`;

    const message = `
╔══════════════════════════════════════════════╗
      FLOOD RISK ALERT SYSTEM — AWS SNS
╚══════════════════════════════════════════════╝

Risk Level  : ${risk}
Location    : ${location}
Rainfall    : ${rainfall} mm
Water Level : ${waterLevel} m
Timestamp   : ${timestamp}

${isHigh
  ? "⚠️  IMMEDIATE ACTION REQUIRED\n   Evacuate low-lying areas immediately.\n   Contact emergency services if needed.\n   Move to higher ground without delay."
  : isMod
  ? "⚡  CAUTION ADVISED\n   Monitor conditions closely.\n   Prepare emergency supplies.\n   Be ready to evacuate if levels rise."
  : "✅  AREA IS SAFE\n   No immediate flood threat detected.\n   Continue to monitor weather updates."}

─────────────────────────────────────────────
This alert was generated by the Flood Risk
Monitoring System powered by:
  • Azure App Service (Flood-Risk ML API)
  • AWS Lambda + SNS (Alert Delivery)
  • AWS S3 + CloudFront (Dashboard)

To unsubscribe, reply STOP or manage your
subscription via the link in your confirmation email.
─────────────────────────────────────────────
    `.trim();

    // ── Step 3: Publish to SNS Topic ───────────────────────────────────────
    await sns.send(new PublishCommand({
      TopicArn: TOPIC_ARN,
      Subject: subject,
      Message: message,
      MessageAttributes: {
        risk: { DataType: "String", StringValue: risk },
        location: { DataType: "String", StringValue: location }
      }
    }));

    return {
      statusCode: 200, headers,
      body: JSON.stringify({ success: true, message: `Alert sent to ${email}`, risk, location })
    };

  } catch (err) {
    console.error("Lambda SNS error:", err);
    return {
      statusCode: 500, headers,
      body: JSON.stringify({ error: "Failed to send alert", details: err.message })
    };
  }
};
